definitions:
  newsHandler.CreateNewsObject:
    properties:
      firstContent:
        type: string
      secondContent:
        type: string
      thirdContent:
        type: string
      title:
        type: string
    type: object
  newsHandler.CreateNewsResponse:
    properties:
      data:
        $ref: '#/definitions/schema.NewsResponse'
      message:
        type: string
    type: object
  newsHandler.DeleteNewsResponse:
    properties:
      data:
        $ref: '#/definitions/schema.NewsResponse'
      message:
        type: string
    type: object
  newsHandler.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  schema.NewsResponse:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      firstContent:
        type: string
      id:
        type: integer
      secondContent:
        type: string
      thirdContent:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  title: WebNewsAPI
paths:
  /news:
    post:
      consumes:
      - application/json
      description: Create a news for the app
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/newsHandler.CreateNewsObject'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/newsHandler.CreateNewsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/newsHandler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/newsHandler.ErrorResponse'
      summary: Create News
      tags:
      - Openings
  /opening:
    delete:
      consumes:
      - application/json
      description: Delete a news
      parameters:
      - description: News identification
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/newsHandler.DeleteNewsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/newsHandler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/newsHandler.ErrorResponse'
      summary: Delete news
      tags:
      - Openings
swagger: "2.0"
